#!/bin/bash

g="\033[1;32m"
y="\033[1;33m"
w="\033[0;37m"

clear
if [ -e chrome-remote-desktop_current_amd64.deb ]
then
    sudo dpkg --install chrome-remote-desktop_current_amd64.deb > /dev/null 2>&1
    sudo apt install --assume-yes --fix-broken > /dev/null 2>&1
    echo -e "${g}[+] ${y}(Chrome Remote Desktop) ${w}telah terinstall"
else
    echo -e "${g}[+] ${w}Menginstall ${y}(Chrome Remote Desktop)"
    wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb > /dev/null 2>&1
    sudo dpkg --install chrome-remote-desktop_current_amd64.deb > /dev/null 2>&1
    sudo apt install --assume-yes --fix-broken > /dev/null 2>&1
fi



echo -e "${g}[+] ${w}Menginstall ${y}(Desktop Environment)"
DEBIAN_FRONTEND=noninteractive
apt install --assume-yes xfce4 desktop-base /dev/null 2>&1
sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
sudo apt install --assume-yes xscreensaver > /dev/null 2>&1
sudo apt install --assume-yes --fix-broken > /dev/null 2>&1
sudo systemctl disable lightdm.service > /dev/null 2>&1



if [ -e google-chrome-stable_current_amd64.deb ]
then
    echo -e "${g}[+] ${y}(Google Chrome) ${w}telah terinstall"
    sudo dpkg --install google-chrome-stable_current_amd64.deb > /dev/null 2>&1
    sudo apt install --assume-yes --fix-broken > /dev/null 2>&1
else
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb > /dev/null 2>&1
    sudo dpkg --install google-chrome-stable_current_amd64.deb > /dev/null 2>&1
    sudo apt install --assume-yes --fix-broken > /dev/null 2>&1
fi



echo -e "${g}[+] ${w}Menginstall ${y}(nano,nautilus)"
sudo apt install nautilus nano -y > /dev/null 2>&1


sudo adduser $USER chrome-remote-desktop> /dev/null 2>&1
echo -e "${w}  Visit: https://remotedesktop.google.com/headless"
read -p "   Command: " cmnd;
su - $USER -c """${cmnd}"""


echo -e "${g}[+] ${w}Selesai silahkan buka Aplikasi/Website Chrome Remote Desktop"
